### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Generator3D

### ISSUE THREAD

**Issue by wskdfw** [amirDahari1/SuperRes#20]
Hi, I am getting the following error while trying to load a saved model :
RuntimeError: Error(s) in loading state_dict for Generator3D:
 Unexpected key(s) in state_dict: "conv_resize_0.weight", "conv_resize_0.bias", "bn_resize_0.weight", "bn_resize_0.bias", "bn_resize_0.running_mean", "bn_resize_0.running_var", "bn_resize_0.num_batches_tracked". 
 size mismatch for conv_minus_1.weight: copying a param with shape torch.Size([512, 3, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 3, 3, 3, 3]).
 size mismatch for conv_minus_1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
 size mismatch for bn_minus_1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
 size mismatch for bn_minus_1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
 size mismatch for bn_minus_1.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
 size mismatch for bn_minus_1.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
 size mismatch for conv_res.0.weight: copying a param with shape torch.Size([512, 512, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
 size mismatch for conv_res.0.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
 size mismatch for conv_res.1.weight: copying a param with shape torch.Size([512, 512, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
 size mismatch for conv_res.1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
 size mismatch for bn_res.0.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
......

**Comment by wskdfw** [comment]
l use `python code/Evaluation.py -d sem_isotropic --with_rotation -volume_size_to_evaluate 236 236 236 -phases_idx 1 -g_image_path nmc_wo_binder.tif` to evaluate the isotropic model,and get the  error

**Comment by wskdfw** [comment]
lt works , thanks!

**Comment by wskdfw** [comment]
I got the output data named `generated_tif1739.tiflow_res ` , so it should be 'xxx.tif ' instead?
It‘s the code from [Evaluation.py](https://github.com/amirDahari1/SuperRes/blob/master/code/Evaluation.py) ：
`imsave(progress_main_dir + '/' + file_name + 'low_res', low_res)`.
 Also, I got `g_weights.pth0.0146`、`g_weights.pth0.0149` in progress.

**Comment by amirDahari1** [comment]
Yes thanks for pointing that out, I'll change that. 
It is still a `.tif` and `.pth` files, you can rename the files to end with the right extensions if you like.

Also, it saves different weights for G during training so you can generate different microstructures without the most recent G while evaluating with the flag (in your case) `-g_epoch_id 0.0146`  

I appreciate all the feedback :)
